---

- name: Clone Dynamic Git Repos
  git:
    repo: "{{ item.address }}"
    dest: "/tmp/nginx/{{ item.address | last }}"
    clone: yes
    update: yes
    recursive: yes
  with_items:
    - "{{ nginx_dynamic_module_2 }}"
  failed_when: false

- name: Create auto-dynamic_nginx Script from Template | NGINX
  template:
    src: auto-dynamic_nginx.j2
    dest: "/tmp/nginx/auto-dynamic_nginx.sh"
    mode: 0775
  register: _auto_dynamic_nginx
  delegate_to: localhost

- debug: var=_auto_dynamic_nginx

- name: Run Created Shell Script
  script: "/tmp/nginx/auto-dynamic_nginx.sh"
  register: _auto_dynamic_nginx_sh

- debug: var=_auto_dynamic_nginx_sh

- name: Message to You!
  debug:
    msg: "Make sure to manually setup your config file to use these modules!"
