---

- name: Install Required PreRequisites
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 32400
  with_items:
    - pcre2-utils
    - zlib1g
    - zlib1g-dbg
    - zlib1g-dev
    - openssl
    - git
    - gcc
    - make
    - libpcre3-dev
    - libssl-dev
    - checkinstall
    - auto-apt

- name: Create Master tmp Directory
  file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory
    mode: 0775

- name: Download NGINX Source
  unarchive:
    src: "{{ nginx_url }}"
