---

- name: Install Required PreRequisites - apt
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 32400
  with_items:
    - "{{ nginx_prerequisites }}"

- name: Create Master tmp Directory
  file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory
    mode: 0775

- name: Run PCRE Steps
  include_tasks: pcre.yml

- name: Run ZLIB Steps
  include_tasks: zlib.yml

- name: Check if OpenSSL is Installed
  shell: if dpkg -l openssl >/dev/null; then echo "true"; fi
  register: openssl_check

- debug: var=openssl_check

- name: Run OpenSSL Steps
  include_tasks: openssl.yml
  when: openssl_check.stdout != "true"
  notify: Delete OpenSSL Script

- name: Git Clone Any Additional Static Modules
  git:
    repo: "{{ item.address }}"
    dest: "/tmp/nginx/{{ item.name }}"
    clone: yes
    update: yes
  with_items:
    - "{{ nginx_module }}"

- name: Run NGINX Steps
  include_tasks: nginx.yml
  notify: Delete All tmp Files
