---
# tasks file for install-nginx

- name: Install Required PreRequisites - apt
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 32400
  with_items:
    - "{{ nginx_prerequisites }}"

- name: Create Master tmp Directory
  file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    state: directory
    mode: 0775

- name: Run PCRE Steps
  include_tasks: pcre.yml

- name: Run ZLIB Steps
  include_tasks: zlib.yml

- name: Run OpenSSL Steps
  include_tasks: openssl.yml

- name: Download NGINX Source
  unarchive:
    src: "{{ nginx_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Git Clone Any Additional Static Modules
  git:
    repo: "{{ nginx_module.address }}"
    dest: "/tmp/nginx/{{ nginx_module.name }}"
    clone: yes
    update: yes

- name: auto-apt run ./configure
  template:
    src: auto-apt_nginx.j2
    dest: "{{ role_path }}/files/auto-apt_nginx.sh"
    mode: 0775
  register: _auto_apt_nginx
  delegate_to: localhost

- debug: var='_auto_apt_nginx'

- name: Run Created Shell Script
  script: files/auto-apt_nginx.sh
  args:
    chdir: "/tmp/nginx/{{ nginx_version }}"
  register: _auto_apt_nginx_sh

- debug: var=_auto_apt_nginx_sh
