---

- name: Create Master tmp Directory
  file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    state: directory
    mode: 0775
  become: true

- name: Create Master tmp Directory | Localhost
  file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  become: true

- name: Download NGINX Source | NGINX
  unarchive:
    src: "{{ nginx_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

- name: Git Clone Any Dynamic Modules
  git:
    repo: "{{ item.address }}"
    dest: "/tmp/nginx/{{ item.name }}"
    clone: yes
    update: yes
    recursive: yes
  with_items:
    - "{{ nginx_dynamic_module }}"
  failed_when: false
  become: true

- name: Create auto-nginx_module Script from Template | Modules
  template:
    src: auto-nginx_module.j2
    dest: "/tmp/nginx/auto-nginx_module.sh"
    mode: 0775
  register: _auto_nginx_module
  delegate_to: localhost
  become: true

- name: Run Created Shell Script | Module
  script: "/tmp/nginx/auto-nginx_module.sh"
  register: _auto_nginx_module_sh
  notify: Delete All tmp Files
  become: true
