---

- name: Install-NGINX | Modules | Create Master tmp Directory
  ansible.builtin.file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    state: directory
    mode: "0775"
  become: true

- name: Install-NGINX | Modules | Create Master tmp Directory
  ansible.builtin.file:
    path: /tmp/nginx
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    state: directory
    mode: "0775"
  delegate_to: localhost
  become: true

- name: Install-NGINX | Modules | Download NGINX Source
  ansible.builtin.unarchive:
    src: "{{ nginx_url }}"
    dest: "/tmp/nginx"
    remote_src: true
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

- name: Install-NGINX | Modules | Git Clone Any Dynamic Modules
  ansible.builtin.git:
    repo: "{{ item.address }}"
    dest: "/tmp/nginx/{{ item.name }}"
    clone: true
    update: true
    version: latest # noqa: latest
    recursive: true
  with_items:
    - "{{ nginx_dynamic_module }}"
  failed_when: false
  become: true

- name: Install-NGINX | Modules | Create auto-nginx_module Script from Template
  ansible.builtin.template:
    src: auto-nginx_module.j2
    dest: "/tmp/nginx/auto-nginx_module.sh"
    mode: "0775"
  register: _auto_nginx_module
  delegate_to: localhost
  become: true

- name: Install-NGINX | Modules | Run Created Shell Script
  ansible.builtin.script: "/tmp/nginx/auto-nginx_module.sh"
  register: _auto_nginx_module_sh
  notify: Delete All tmp Files
  become: true
