---
# tasks file for nginx.yml

- name: Download NGINX Source | NGINX
  unarchive:
    src: "{{ nginx_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
  become: true

- name: Git Clone Any Additional Static Modules
  git:
    repo: "{{ item.address }}"
    dest: "/tmp/nginx/{{ item.name }}"
    clone: yes
    update: yes
    recursive: yes
  loop: "{{ nginx_module }}"
  failed_when: false
  become: true

- name: Git Clone Any Additional Dynamic Modules
  git:
    repo: "{{ item.address }}"
    dest: "/tmp/nginx/{{ item.name }}"
    clone: yes
    update: yes
    recursive: yes
  loop: "{{ nginx_dynamic_module }}"
  failed_when: false
  become: true

- name: Create auto-apt_nginx Script from Template | NGINX
  template:
    src: auto-apt_nginx.j2
    dest: "/tmp/nginx/auto-apt_nginx.sh"
    mode: 0775
  register: _auto_apt_nginx
  delegate_to: localhost
  become: true

- name: Run Created Shell Script | NGINX
  script: "/tmp/nginx/auto-apt_nginx.sh"
  register: _auto_apt_nginx_sh
  become: true
