---
# tasks file for nginx.yml

- name: Download NGINX Source
  unarchive:
    src: "{{ nginx_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: auto-apt run ./configure
  template:
    src: auto-apt_nginx.j2
    dest: "{{ role_path }}/files/auto-apt_nginx.sh"
    mode: 0775
  register: _auto_apt_nginx
  delegate_to: localhost

- debug: var='_auto_apt_nginx'

- name: Run Created Shell Script
  script: files/auto-apt_nginx.sh
  args:
    chdir: "/tmp/nginx/{{ nginx_version }}"
  register: _auto_apt_nginx_sh

- debug: var=_auto_apt_nginx_sh

- handlers: Delete OpenSSL Script
