---
# tasks file for nginx.yml

- name: Download NGINX Source | NGINX
  ansible.builtin.unarchive:
    src: "{{ nginx_url }}"
    dest: "/tmp/nginx"
    remote_src: true
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

- name: Create auto-apt_nginx Script from Template | NGINX
  ansible.builtin.template:
    src: auto-apt_nginx.j2
    dest: "/tmp/nginx/auto-apt_nginx.sh"
    mode: 0775
  register: _auto_apt_nginx
  delegate_to: localhost
  become: true

- name: Run Created Shell Script | NGINX
  ansible.builtin.script: "/tmp/nginx/auto-apt_nginx.sh"
  register: _auto_apt_nginx_sh
  notify: Delete All tmp Files
  become: true

- name: Create NGINX Service File
  ansible.builtin.template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
    mode: 0775
  notify: Enable NGINX Service
  become: true
