---
# Task list for openssl

- name: Install-NGINX | openssl.yml | Download openssl
  ansible.builtin.unarchive:
    src: "{{ quic_openssl_url }}"
    dest: "/tmp/nginx"
    remote_src: true
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

- name: Install-NGINX | openssl.yml | Create auto-apt_openssl Script from Template
  ansible.builtin.template:
    src: auto-apt_openssl.j2
    dest: "/tmp/nginx/auto-apt_openssl.sh"
    mode: "0775"
  register: _auto_apt_openssl
  delegate_to: localhost
  become: true

- name: Install-NGINX | openssl.yml | Run Created Shell Script
  ansible.builtin.script: /tmp/nginx/auto-apt_openssl.sh
  register: _auto_apt_openssl_sh
  notify: Delete OpenSSL Script
  become: true
