---
# Task list for PCRE

- name: Download PCRE | PCRE
  ansible.builtin.unarchive:
    src: "{{ pcre_url }}"
    dest: "/tmp/nginx"
    remote_src: true
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

- name: Create auto-apt_pcre Script from Template | PCRE
  ansible.builtin.template:
    src: auto-apt_pcre.j2
    dest: "/tmp/nginx/auto-apt_pcre.sh"
    mode: 0775
  register: _auto_apt_pcre
  delegate_to: localhost
  become: true

- name: Run Created Shell Script | PCRE
  ansible.builtin.script: "/tmp/nginx/auto-apt_pcre.sh"
  register: _auto_apt_pcre_sh
  become: true
  notify: Delete PCRE Script
