---
# Task list for PCRE

- name: Install-NGINX | pcre.yml | Try installing the apt version
  when: ansible_os_family == 'Debian'
  ansible.builtin.package:
    name: pcre2-utils
    state: present
  register: _pcre2_apt

# using the block to go around compiling the code
- name: Install-NGINX | pcre.yml | Block | Compile PCRE2
  block:
    - name: Install-NGINX | pcre.yml | Download PCRE
      ansible.builtin.unarchive:
        src: "{{ pcre_url }}"
        dest: "/tmp/nginx"
        remote_src: true
        owner: "{{ ansible_user_uid | int }}"
        group: "{{ ansible_user_gid | int }}"
      become: true

    - name: Install-NGINX | pcre.yml | Create auto-apt_pcre Script from Template
      ansible.builtin.template:
        src: auto-apt_pcre.j2
        dest: "/tmp/nginx/auto-apt_pcre.sh"
        mode: "0775"
      register: _auto_apt_pcre
      delegate_to: localhost
      become: true

    - name: Install-NGINX | pcre.yml | Run Created Shell Script
      ansible.builtin.script: "/tmp/nginx/auto-apt_pcre.sh"
      register: _auto_apt_pcre_sh
      become: true
      notify: Delete PCRE Script
  when: _pcre2_apt is installed
