---
# Task list for PCRE

- name: NGINX | pcre.yml | Download PCRE
  ansible.builtin.unarchive:
    src: "{{ pcre_url }}"
    dest: "/tmp/nginx"
    remote_src: true
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

- name: NGINX | pcre.yml | Create auto-apt_pcre Script from Template
  ansible.builtin.template:
    src: auto-apt_pcre.j2
    dest: "/tmp/nginx/auto-apt_pcre.sh"
    mode: "0775"
  register: _auto_apt_pcre
  delegate_to: localhost
  become: true

- name: NGINX | pcre.yml | Run Created Shell Script
  ansible.builtin.script: "/tmp/nginx/auto-apt_pcre.sh"
  register: _auto_apt_pcre_sh
  become: true
  notify: Delete PCRE Script
