---
# Task list for ZLIB

- name: Download ZLIB
  unarchive:
    src: "{{ zlib_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: auto-apt run ./configure | ZLIB
  template:
    src: auto-apt_zlib.j2
    dest: "{{ role_path }}/files/auto-apt_zlib.sh"
    mode: 0775
  register: _auto_apt_zlib
  delegate_to: localhost

- debug: var='_auto_apt_zlib'

- name: Run Created Shell Script | ZLIB
  script: files/auto-apt_zlib.sh
  args:
    chdir: "/tmp/nginx/{{ zlib_version }}"
  register: _auto_apt_zlib_sh

- debug: var=_auto_apt_zlib_sh

- handlers: Delete OpenSSL Script
