---
# Task list for ZLIB

<<<<<<< HEAD
- name: Download ZLIB | ZLIB
=======

- name: NGINX | zlib.yml | Download ZLIB
>>>>>>> 971d87c74c3fff8d3efd64d99b4d73551de5fca7
  ansible.builtin.unarchive:
    src: "{{ zlib_url }}"
    dest: "/tmp/nginx"
    remote_src: true
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
  become: true

<<<<<<< HEAD
- name: Create auto-apt_zlib Script from Template | ZLIB
=======

- name: NGINX | zlib.yml | Create auto-apt_zlib Script from Template
>>>>>>> 971d87c74c3fff8d3efd64d99b4d73551de5fca7
  ansible.builtin.template:
    src: auto-apt_zlib.j2
    dest: "/tmp/nginx/auto-apt_zlib.sh"
    mode: "0775"
  register: _auto_apt_zlib
  delegate_to: localhost
  become: true

<<<<<<< HEAD
- name: Run Created Shell Script | ZLIB
=======
- name: NGINX | zlib.yml | Run Created Shell Script
>>>>>>> 971d87c74c3fff8d3efd64d99b4d73551de5fca7
  ansible.builtin.script: "/tmp/nginx/auto-apt_zlib.sh"
  register: _auto_apt_zlib_sh
  become: true
  notify: Delete ZLIB Script
