---

- name: Delete OpenSSL Script
  ansible.builtin.file:
    path: files/auto-apt_openssl.sh
    state: absent
  delegate_to: localhost

- name: Delete PCRE Script
  ansible.builtin.file:
    path: files/auto-apt_pcre.sh
    state: absent
  delegate_to: localhost

- name: Delete ZLIB Script
  ansible.builtin.file:
    path: files/auto-apt_zlib.sh
    state: absent
  delegate_to: localhost

- name: Delete NGINX Script
  ansible.builtin.file:
    path: files/auto-apt_nginx.sh
    state: absent
  delegate_to: localhost

- name: Delete All tmp Files
  ansible.builtin.file:
    path: /tmp/nginx
    state: absent
  become: true

- name: Enable NGINX Service
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: nginx.service
    state: started

- name: Reload NGINX
  ansible.builtin.command: '/etc/init.d/nginx upgrade_nginx'
  become: true
