galaxy_info:
  author: Justin Partain
  description: Install NGINX and dependencies From Source
  company: JPCDI

  license: license (GPLv3)

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
      - trusty
      - xenial
      - bionic
    - name: Debian
      versions:
      - stretch
      - wheezy
      - buster

  galaxy_tags:
    - nginx

dependencies: []
